/**:
  ros__parameters:
    x0: 0.0
    y0: 0.0
    theta0: 0.0
    obstacles:
      x: [-0.6, 0.7, 0.5]
      y: [-0.8, -0.7, 0.9]
      r: 0.038
      h: 0.25
    walls:
      x_lenght: 3.5
      y_lenght: 3.5
      h: 0.25
      w: 0.10
